export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const DISPLAY_STUFF = "DISPLAY_STUFF";
export const DISPLAY_DETAILS = "DISPLAY_DETAILS";
export const DISPLAY_MSG = "DISPLAY_MSG";


